apiVersion: apps/v1
kind: Deployment
metadata:
  name: binarycalculator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: binarycalculator
  template:
    metadata:
      labels:
        app: binarycalculator
    spec:
      containers:
        - image: gcr.io/bubbly-triumph-380321/binarycalculator
          name: binarycalculator
          ports:
            - containerPort: 8080
              name: binarycalculator
